In [6]:
import requests
from io import BytesIO
import pandas as pd

In [4]:
data = requests.get('https://data.chhs.ca.gov/dataset/dace89fc-69ec-4fe8-a8f4-ddfbdb053020/resource/f3d8578f-a9bf-4f6a-a224-7e5b522cbd76/download/ca-oshpd-cancer-surgeries-gachospitals-20132021.csv').content
csv = BytesIO()
csv.write(data)
csv.seek(0)

0

In [7]:
df = pd.read_csv('https://data.chhs.ca.gov/dataset/dace89fc-69ec-4fe8-a8f4-ddfbdb053020/resource/f3d8578f-a9bf-4f6a-a224-7e5b522cbd76/download/ca-oshpd-cancer-surgeries-gachospitals-20132021.csv', encoding = "cp1254")

In [8]:
df

,Year,County,Hospital,OSHPDID,Surgery,# of Cases (ICD 9),# of Cases (ICD 10),LONGITUDE,LATITUDE
0,2013,NaN,Statewide,NaN,Colon,7128.0,NaN,NaN,NaN
1,2013,NaN,Statewide,NaN,Bladder,892.0,NaN,NaN,NaN
2,2013,NaN,Statewide,NaN,Rectum,2128.0,NaN,NaN,NaN
3,2013,NaN,Statewide,NaN,Breast,25829.0,NaN,NaN,NaN
4,2013,NaN,Statewide,NaN,Brain,2719.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
17612,2021,Yuba,Adventist Health and Rideout,106580996.0,Rectum,NaN,3.0,-121.593602,39.138805
17613,2021,Yuba,Adventist Health and Rideout,106580996.0,Prostate,NaN,3.0,-121.593602,39.138805
17614,2021,Yuba,Adventist Health and Rideout,106580996.0,Lung,NaN,5.0,-121.593602,39.138805
17615,2021,Yuba,Adventist Health and Rideout,106580996.0,Colon,NaN,9.0,-121.593602,39.138805
17616,2021,Yuba,Adventist Health and Rideout,106580996.0,Breast,NaN,26.0,-121.593602,39.138805

In [9]:
df.columns

Index(['Year', 'County', 'Hospital', 'OSHPDID', 'Surgery',
       '# of Cases (ICD 9)', '# of Cases (ICD 10)', 'LONGITUDE', 'LATITUDE'],
      dtype='object')

In [10]:
len(df)

17617

In [13]:
df['Year'].isna().sum()

0

In [14]:
for coluna in df.columns:
  print(f"{coluna}: {df[coluna].isna().sum()}")

Year: 0
County: 99
Hospital: 0
OSHPDID: 99
Surgery: 0
# of Cases (ICD 9): 11888
# of Cases (ICD 10): 5729
LONGITUDE: 106
LATITUDE: 106

In [16]:
df.dropna()

Empty DataFrame
Columns: [Year, County, Hospital, OSHPDID, Surgery, # of Cases (ICD 9), # of Cases (ICD 10), LONGITUDE, LATITUDE]
Index: []

In [17]:
df.loc[0]

Year                        2013
County                       NaN
Hospital               Statewide
OSHPDID                      NaN
Surgery                    Colon
# of Cases (ICD 9)        7128.0
# of Cases (ICD 10)          NaN
LONGITUDE                    NaN
LATITUDE                     NaN
Name: 0, dtype: object

In [24]:
df.set_index('Hospital').iloc[[5, 50, 2000]]

,Year,County,OSHPDID,Surgery,# of Cases (ICD 9),# of Cases (ICD 10),LONGITUDE,LATITUDE
Hospital,,,,,,,,
Statewide,2013,NaN,NaN,Pancreas,819.0,NaN,NaN,NaN
Alta Bates Summit Medical Center – Summit Campus – Hawthorne,2013,Alameda,106010937.0,Rectum,14.0,NaN,-122.26257,37.82106
Kaiser Foundation Hospital – Hayward,2014,Alameda,106010858.0,Prostate,2.0,NaN,-122.09338,37.62593

In [22]:
df.set_index('Hospital').loc['Statewide']

,Year,County,OSHPDID,Surgery,# of Cases (ICD 9),# of Cases (ICD 10),LONGITUDE,LATITUDE
Hospital,,,,,,,,
Statewide,2013,NaN,NaN,Colon,7128.0,NaN,NaN,NaN
Statewide,2013,NaN,NaN,Bladder,892.0,NaN,NaN,NaN
Statewide,2013,NaN,NaN,Rectum,2128.0,NaN,NaN,NaN
Statewide,2013,NaN,NaN,Breast,25829.0,NaN,NaN,NaN
Statewide,2013,NaN,NaN,Brain,2719.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
Statewide,2020,NaN,NaN,Lung,NaN,3067.0,NaN,NaN
Statewide,2020,NaN,NaN,Pancreas,NaN,1092.0,NaN,NaN
Statewide,2020,NaN,NaN,Prostate,NaN,3662.0,NaN,NaN
Statewide,2020,NaN,NaN,Rectum,NaN,3168.0,NaN,NaN
Statewide,2020,NaN,NaN,Stomach,NaN,960.0,NaN,NaN

In [32]:
condicao1 = (df[df['Surgery']!='Prostate'])
condicao2 = (df['County'].str.startswith('Y'))

In [33]:
df['County'].str.startswith('Y', na=False)

0        False
1        False
2        False
3        False
4        False
         ...
17612     True
17613     True
17614     True
17615     True
17616     True
Name: County, Length: 17617, dtype: bool

In [35]:
df[(~df['# of Cases (ICD 10)'].isna()) & (df['# of Cases (ICD 9)'].isna())]

,Year,County,Hospital,OSHPDID,Surgery,# of Cases (ICD 9),# of Cases (ICD 10),LONGITUDE,LATITUDE
5729,2016,NaN,Statewide,NaN,Bladder,NaN,1054.0,NaN,NaN
5730,2016,NaN,Statewide,NaN,Brain,NaN,3162.0,NaN,NaN
5731,2016,NaN,Statewide,NaN,Breast,NaN,27495.0,NaN,NaN
5732,2016,NaN,Statewide,NaN,Colon,NaN,7623.0,NaN,NaN
5733,2016,NaN,Statewide,NaN,Esophagus,NaN,410.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
17612,2021,Yuba,Adventist Health and Rideout,106580996.0,Rectum,NaN,3.0,-121.593602,39.138805
17613,2021,Yuba,Adventist Health and Rideout,106580996.0,Prostate,NaN,3.0,-121.593602,39.138805
17614,2021,Yuba,Adventist Health and Rideout,106580996.0,Lung,NaN,5.0,-121.593602,39.138805
17615,2021,Yuba,Adventist Health and Rideout,106580996.0,Colon,NaN,9.0,-121.593602,39.138805
17616,2021,Yuba,Adventist Health and Rideout,106580996.0,Breast,NaN,26.0,-121.593602,39.138805

In [40]:
icd_9 = df[df['# of Cases (ICD 10)'].isna()]['# of Cases (ICD 9)']
icd_10 = df[~df['# of Cases (ICD 10)'].isna()]['# of Cases (ICD 10)']

uniao_icd = pd.concat([icd_9, icd_10])

In [41]:
uniao_icd

0         7128.0
1          892.0
2         2128.0
3        25829.0
4         2719.0
          ...
17612        3.0
17613        3.0
17614        5.0
17615        9.0
17616       26.0
Length: 17617, dtype: float64

In [42]:
df['uniao_icd'] = uniao_icd[1:2]

In [43]:
df

,Year,County,Hospital,OSHPDID,Surgery,# of Cases (ICD 9),# of Cases (ICD 10),LONGITUDE,LATITUDE,uniao_icd
0,2013,NaN,Statewide,NaN,Colon,7128.0,NaN,NaN,NaN,NaN
1,2013,NaN,Statewide,NaN,Bladder,892.0,NaN,NaN,NaN,892.0
2,2013,NaN,Statewide,NaN,Rectum,2128.0,NaN,NaN,NaN,NaN
3,2013,NaN,Statewide,NaN,Breast,25829.0,NaN,NaN,NaN,NaN
4,2013,NaN,Statewide,NaN,Brain,2719.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
17612,2021,Yuba,Adventist Health and Rideout,106580996.0,Rectum,NaN,3.0,-121.593602,39.138805,NaN
17613,2021,Yuba,Adventist Health and Rideout,106580996.0,Prostate,NaN,3.0,-121.593602,39.138805,NaN
17614,2021,Yuba,Adventist Health and Rideout,106580996.0,Lung,NaN,5.0,-121.593602,39.138805,NaN
17615,2021,Yuba,Adventist Health and Rideout,106580996.0,Colon,NaN,9.0,-121.593602,39.138805,NaN
17616,2021,Yuba,Adventist Health and Rideout,106580996.0,Breast,NaN,26.0,-121.593602,39.138805,NaN

In [45]:
df.drop(['# of Cases (ICD 9)', '# of Cases (ICD 10)'], axis = 1)

,Year,County,Hospital,OSHPDID,Surgery,LONGITUDE,LATITUDE,uniao_icd
0,2013,NaN,Statewide,NaN,Colon,NaN,NaN,NaN
1,2013,NaN,Statewide,NaN,Bladder,NaN,NaN,892.0
2,2013,NaN,Statewide,NaN,Rectum,NaN,NaN,NaN
3,2013,NaN,Statewide,NaN,Breast,NaN,NaN,NaN
4,2013,NaN,Statewide,NaN,Brain,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
17612,2021,Yuba,Adventist Health and Rideout,106580996.0,Rectum,-121.593602,39.138805,NaN
17613,2021,Yuba,Adventist Health and Rideout,106580996.0,Prostate,-121.593602,39.138805,NaN
17614,2021,Yuba,Adventist Health and Rideout,106580996.0,Lung,-121.593602,39.138805,NaN
17615,2021,Yuba,Adventist Health and Rideout,106580996.0,Colon,-121.593602,39.138805,NaN
17616,2021,Yuba,Adventist Health and Rideout,106580996.0,Breast,-121.593602,39.138805,NaN

In [47]:
df['OSHPDID'].fillna(0)

0                0.0
1                0.0
2                0.0
3                0.0
4                0.0
            ...
17612    106580996.0
17613    106580996.0
17614    106580996.0
17615    106580996.0
17616    106580996.0
Name: OSHPDID, Length: 17617, dtype: float64